# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opossum < Formula
  desc "A Docker Compose-like orchestrator for Apple's container runtime"
  homepage "https://github.com/suruseas/opossum"
  version "0.19.0"
  license "MIT"

  depends_on "container"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/suruseas/opossum/releases/download/v0.19.0/opossum_0.19.0_darwin_arm64.tar.gz"
    sha256 "72d2becda8c3d377c95c2a52e66aaad8c1120560466cdd9711af6a1201c55223"

    define_method(:install) do
      bin.install "opossum"
    end
  end
end
