# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opossum < Formula
  desc "A Docker Compose-like orchestrator for Apple's container runtime"
  homepage "https://github.com/suruseas/opossum"
  version "0.6.0"
  license "MIT"

  depends_on "container"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/suruseas/opossum/releases/download/v0.6.0/opossum_0.6.0_darwin_arm64.tar.gz"
    sha256 "dd56b1a86ebe74f48bf5933c42163a2fabc6271e51ea7212de9e52c2bcf681ef"

    define_method(:install) do
      bin.install "opossum"
    end
  end
end
