# This file was generated by GoReleaser. DO NOT EDIT.
cask "opossum" do
  version "0.24.2"

  on_macos do
    on_arm do
      sha256 "481663e33c7c317c828a0b8273014c7b8139ee2abfdcfdb2aaf111d2f349113a"
      url "https://github.com/suruseas/opossum/releases/download/v#{version}/opossum_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "opossum"
  desc "A Docker Compose-like orchestrator for Apple's container runtime"
  homepage "https://github.com/suruseas/opossum"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "container",
    ]

  binary "opossum"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opossum"]
    end
  end

  # No zap stanza required
end
