# This file was generated by GoReleaser. DO NOT EDIT.
cask "opossum" do
  version "0.27.0"

  on_macos do
    on_arm do
      sha256 "f990266b74fb912de3c98ad408770121949f172f12ad0292f48728df736b3a90"
      url "https://github.com/suruseas/opossum/releases/download/v#{version}/opossum_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "opossum"
  desc "A Docker Compose-like orchestrator for Apple's container runtime"
  homepage "https://github.com/suruseas/opossum"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "container",
    ]

  binary "opossum"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opossum"]
    end
  end

  # No zap stanza required
end
