# This file was generated by GoReleaser. DO NOT EDIT.
cask "opossum" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/opossum"]
    end
  end

  version "0.45.0"

  on_macos do
    on_arm do
      sha256 "db61563a7006e5a1829228c03c5f3dc26547b939565450fe1d089916eead0d4a"
      url "https://github.com/suruseas/opossum/releases/download/v#{version}/opossum_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "opossum"
  desc "A Docker Compose-like orchestrator for Apple's container runtime"
  homepage "https://github.com/suruseas/opossum"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "container",
    ]

  binary "opossum"

  # No zap stanza required
end
